#!/usr/bin/env ruby
# frozen_string_literal: true

require "genron_sf/ebook/kougai_generator"

year = GenronSF::Term.latest.year
number = GenronSF::Subject.list(year:).to_a.last.number
subject = GenronSF::Subject.get(year:, number:)
generator = GenronSF::EBook::KougaiGenerator.new(subject)
generator.generate
